### ISSUE TITLE
Remove reference to zero coefficients in vlasov stream gen_geo kernels

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylcas#20]
vlasov gen_geo kernels for the streaming kernel do not account for the fact that alpha (the advection velocity) is linear in velocity coordinates, and therefore coefficients for quadratic monomials (for hybrid and p>1) are zero. This results in a bunch of calculations and write statements that just deal with zeros.

This is possibly just a result of using the wrong (maxima) writing workflow. We should fix this to reduce the size of the kernel.

**Comment by JunoRavin** [comment]
I believe I solved this issue with commit b6f86af and the gkylzero commit https://github.com/ammarhakim/gkylzero/commit/f69d1ac509e7588098f299bbac59754b65b7dd44
